services:
    _defaults:
        autowire: true
        autoconfigure: true

    Neimheadh\Bundle\AngularBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'
